vtx_sel: ( SDVSecVtx_dphiMET<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack>=2)&&( SDVSecVtx_dphijet0>1 ) && (SDVSecVtx_ndof>1) && (SDVSecVtx_mapveto==0) && (SDVSecVtx_nnonPUTrack>0) 
vtx_sel_loose: ( SDVSecVtx_dphiMET<1.5 )&&(SDVSecVtx_pAngle>0.2)&&( SDVSecVtx_dphijet0>1 ) && (SDVSecVtx_ndof>1) && (SDVSecVtx_mapveto==0) && (SDVSecVtx_nnonPUTrack>0) 
vtx_g2tk_sel: ( SDVSecVtx_dphiMET<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack>2)&&( SDVSecVtx_dphijet0>1 ) && (SDVSecVtx_ndof>1) && (SDVSecVtx_mapveto==0) && (SDVSecVtx_nnonPUTrack>0) 
vtx_2tk_sel: ( SDVSecVtx_dphiMET<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack==2)&&( SDVSecVtx_dphijet0>1 ) && (SDVSecVtx_ndof>1) && (SDVSecVtx_mapveto==0) && (SDVSecVtx_nnonPUTrack>0) 
vtx_sel_val1: ( SDVSecVtx_dphiMET<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack==1)&&( SDVSecVtx_dphijet0>1 ) && (SDVSecVtx_ndof>1) && (SDVSecVtx_mapveto==0) && (SDVSecVtx_nnonPUTrack>0) 
vtx_sel_val2: ( SDVSecVtx_dphiMET<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack==0)&&( SDVSecVtx_dphijet0>1 ) && (SDVSecVtx_ndof>1) && (SDVSecVtx_mapveto==0) && (SDVSecVtx_nnonPUTrack>0) 

jet_sel: (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (Jet_pt>20)
jet_selHEM: (Jet_jetId==6) 

muon_sel: (Muon_looseId>0) && (Muon_eta<2.4) && (Muon_pt>10)
ele_sel: (Electron_cutBased>=1) && (Electron_eta<2.5) && (Electron_pt>10)
photon_sel: (Photon_cutBased>=1) && (Photon_eta<2.5) && (Photon_pt>15)
tau_sel: (Tau_idDecayModeOldDMs>=1) && (Tau_eta<2.3) && (Tau_pt>18)

presel: MET_pt_corr>400 && HLT_PFMETNoMu120_PFMHTNoMu120_IDTight && nJet_sel>0 && leadingjet_pt>100 && Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_hfNoisyHitsFilter && Flag_BadChargedCandidateFilter && Flag_eeBadScFilter && Flag_ecalBadCalibFilter && nJetHEM==0 && dphi_MET_jet0>1.0 && nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0

nJetHEM: "(run>=319077)*Sum((Jet_eta_selHEM>-3.0) && (Jet_eta_selHEM<-1.3) && (Jet_phi_selHEM>-1.57) && (Jet_phi_selHEM<-0.87))"

corrections:
  PU:
    "2017":
      path: "/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2017_UL/puWeights.json.gz"
      name: "Collisions17_UltraLegacy_goldenJSON"
      mode: "nominal"
    "2018":
      path: "/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2018_UL/puWeights.json.gz"
      name: "Collisions18_UltraLegacy_goldenJSON"
      mode: "nominal"
  met:
    mode: "nominal"

mapveto:
  data_path: "/eos/vbc/group/cms/ang.li/material_map/material_map_2tk_loose.root"
  mc_path: "/eos/vbc/group/cms/ang.li/material_map/material_map_MC_2tk_loose.root"

weights:

mcweights:
  - L1PreFiringWeight_Nom

new_variables:

  MET_corr:     SDV::METXYCorr_Met_MetPhi(new_MET_pt,new_MET_phi,run,"2018",false,PV_npvs)
  MET_pt_corr:  MET_corr.first
  MET_phi_corr: MET_corr.second

  Jet_pt_sel: ['Jet_pt[{0}]',jet_sel] 
  Jet_eta_sel: ['Jet_eta[{0}]',jet_sel]
  Jet_phi_sel: ['Jet_phi[{0}]',jet_sel]
  Jet_chHEF_sel: ['Jet_chHEF[{0}]',jet_sel]
  Jet_neHEF_sel: ['Jet_neHEF[{0}]',jet_sel]
  Jet_eta_selHEM: ['Jet_eta[{0}]',jet_selHEM]
  Jet_phi_selHEM: ['Jet_phi[{0}]',jet_selHEM]
  nJet_sel: ['Sum({0})',jet_sel]

  leadingjet_pt: Jet_pt_sel[0]
  leadingjet_phi: Jet_phi_sel[0]
  leadingjet_eta: Jet_eta_sel[0]
  leadingjet_chHEF: Jet_chHEF_sel[0]
  leadingjet_neHEF: Jet_neHEF_sel[0]

  dphi_MET_jet0: acos(cos(leadingjet_phi-MET_phi_corr))

  SDVTrack_dphi_jet0: acos(cos(SDVTrack_phi-leadingjet_phi))
  SDVTrack_dphi_MET: acos(cos(SDVTrack_phi-MET_phi_corr))
  SDVTrack_dxydzratio: abs(SDVTrack_dxy/SDVTrack_dz)
  SDVTrack_isGoodTrack: ( (abs(SDVTrack_dxy)/SDVTrack_dxyError)>4 ) && (SDVTrack_normalizedChi2 < 5) && (SDVTrack_numberOfValidHits>13) && ( (SDVTrack_ptError/SDVTrack_pt)<0.015 ) && ( SDVTrack_dxydzratio>0.25 ) && ( SDVTrack_dphi_jet0>1 ) && ( SDVTrack_dphi_MET<1.5 ) && (SDVTrack_pfRelIso03_all<5)
  nGoodTrack: ['Sum(SDVTrack_isGoodTrack)']
  SDVSecVtx_nGoodTrack: SDVSecVtx_nGoodTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isGoodTrack,nSDVSecVtx)
  SDVTrack_isnonPU: ( SDVTrack_dxydzratio>0.25 )
  SDVSecVtx_nnonPUTrack: SDVSecVtx_nselTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isnonPU,nSDVSecVtx)
  SDVSecVtx_dphiMET: 'acos(cos(SDVSecVtx_L_phi-MET_phi_corr))'
  SDVSecVtx_dphijet0: 'acos(cos(SDVSecVtx_L_phi-leadingjet_phi))'
  SDVSecVtx_L_eta_abs: "abs(SDVSecVtx_L_eta)"
  nSDVSecVtx_sel_loose: ['Sum({0})', vtx_sel_loose]
  nSDVSecVtx_sel: ['Sum({0})', vtx_sel]
  nSDVSecVtx_sel_2tk: ['Sum({0})', vtx_2tk_sel]
  nSDVSecVtx_sel_g2tk: ['Sum({0})', vtx_g2tk_sel]
  nSDVSecVtx_sel_val1: ['Sum({0})', vtx_sel_val1]
  nSDVSecVtx_sel_val2: ['Sum({0})', vtx_sel_val2]

  nMuon_sel: ['Sum({0})', muon_sel]
  nEle_sel: ['Sum({0})', ele_sel]
  nPhoton_sel: ['Sum({0})', photon_sel]
  nTau_sel: ['Sum({0})', tau_sel]

  SDVSecVtx_LxySig_max_val1: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_val1]
  SDVSecVtx_LxySig_max_val2: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_val2]
  SDVSecVtx_LxySig_max: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel]
  SDVSecVtx_LxySig_max_g2tk: ['Max(SDVSecVtx_LxySig[{0}])',vtx_g2tk_sel]
  SDVSecVtx_LxySig_max_2tk: ['Max(SDVSecVtx_LxySig[{0}])',vtx_2tk_sel]
  SDVSecVtx_LxySig_loose: ['SDVSecVtx_LxySig[{0}]',vtx_sel_loose]
  SDVSecVtx_nGoodTrack_loose: ['SDVSecVtx_nGoodTrack[{0}]',vtx_sel_loose]
  LeadingVtx_idx: 'Leading_Vtx_Idx(SDVSecVtx_nGoodTrack_loose,SDVSecVtx_LxySig_loose)'
  LeadingVtx_LxySig: 'SDVSecVtx_LxySig_loose[LeadingVtx_idx]'
  LeadingVtx_nGoodTrack: 'SDVSecVtx_nGoodTrack_loose[LeadingVtx_idx]'

  #SDVSecVtx_LxySig_MLsel_max: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_ML]
new_variables_mc:
  LLP_ctau0: "LLP_ctau[0]"
  LLP_ctau1: "LLP_ctau[1]"
  LLP_decaymode0: "LLP_decaymode[0]"
  LLP_decaymode1: "LLP_decaymode[1]"

savepkl:
  - evt_weight
  - LLP_ctau0
  - LLP_ctau1
  - LLP_decaymode0
  - LLP_decaymode1

regions:
  All: 
  Vtx: nSDVSecVtx_sel_loose>0
  SRs_g2tk: nSDVSecVtx_sel_g2tk>0
  SR_g2tk: nSDVSecVtx_sel_g2tk>0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_g2tk>20.0
  SR_g2tk_CRlowMET: nSDVSecVtx_sel_g2tk>0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_g2tk>20.0
  SR_g2tk_CRlowLxy:  nSDVSecVtx_sel_g2tk>0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_g2tk<20.0
  SR_g2tk_CRlowLxylowMET: nSDVSecVtx_sel_g2tk>0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_g2tk<20.0
  SRs_2tk: nSDVSecVtx_sel_2tk>0 && nSDVSecVtx_sel_g2tk==0
  SR_2tk: nSDVSecVtx_sel_2tk>0 && nSDVSecVtx_sel_g2tk==0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_2tk>20.0
  SR_2tk_CRlowMET: nSDVSecVtx_sel_2tk>0 && nSDVSecVtx_sel_g2tk==0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_2tk>20.0
  SR_2tk_CRlowLxy:  nSDVSecVtx_sel_2tk>0 && nSDVSecVtx_sel_g2tk==0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_2tk<20.0
  SR_2tk_CRlowLxylowMET: nSDVSecVtx_sel_2tk>0 && nSDVSecVtx_sel_g2tk==0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_2tk<20.0
  #SRs: nSDVSecVtx_sel>0
  #SR: nSDVSecVtx_sel>0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max>20.0
  #SR_CRlowMET: nSDVSecVtx_sel>0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max>20.0
  #SR_CRlowLxy:  nSDVSecVtx_sel>0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max<20.0
  #SR_CRlowLxylowMET: nSDVSecVtx_sel>0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max<20.0
  VR1s: nSDVSecVtx_sel==0 && nSDVSecVtx_sel_val1>0
  VR1: nSDVSecVtx_sel==0 && nSDVSecVtx_sel_val1>0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_val1>20.0
  VR1_CRlowMET: nSDVSecVtx_sel_val1>0 && nSDVSecVtx_sel==0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_val1>20.0
  VR1_CRlowLxy: nSDVSecVtx_sel_val1>0 && nSDVSecVtx_sel==0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_val1<20.0
  VR1_CRlowLxylowMET: nSDVSecVtx_sel_val1>0 && nSDVSecVtx_sel==0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_val1<20.0
  VR2s: nSDVSecVtx_sel==0 && nSDVSecVtx_sel_val1==0 && nSDVSecVtx_sel_val2>0
  VR2: nSDVSecVtx_sel==0 && nSDVSecVtx_sel_val1==0 && nSDVSecVtx_sel_val2>0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_val2>20.0
  VR2_CRlowMET: nSDVSecVtx_sel_val2>0 && nSDVSecVtx_sel_val1==0 && nSDVSecVtx_sel==0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_val2>20.0
  VR2_CRlowLxy: nSDVSecVtx_sel_val2>0 && nSDVSecVtx_sel_val1==0 && nSDVSecVtx_sel==0 && MET_pt_corr>700 && SDVSecVtx_LxySig_max_val2<20.0
  VR2_CRlowLxylowMET: nSDVSecVtx_sel_val2>0 && nSDVSecVtx_sel_val1==0 && nSDVSecVtx_sel==0 && MET_pt_corr<700 && SDVSecVtx_LxySig_max_val2<20.0

event_variables:
- nSDVSecVtx_sel
- nSDVSecVtx_sel_val1
- nSDVSecVtx_sel_val2
- nSDVSecVtx
- nMuon_sel
- nEle_sel
- nPhoton_sel
- nTau_sel
- nJet
- nJet_sel
- MET_pt
- MET_phi
- MET_pt_corr
- MET_phi_corr
- dphi_MET_jet0
- leadingjet_pt
- leadingjet_phi
- leadingjet_eta
- leadingjet_chHEF
- leadingjet_neHEF
- SDVSecVtx_LxySig_max
- SDVSecVtx_LxySig_max_val1
- SDVSecVtx_LxySig_max_val2
- SDVSecVtx_LxySig_max_g2tk
- SDVSecVtx_LxySig_max_2tk
- LeadingVtx_LxySig
- LeadingVtx_nGoodTrack
- evt_weight
event_variables_mc:
- puweight
event_2d_plots:
  - [MET_pt_corr,SDVSecVtx_LxySig_max]
  - [MET_pt_corr,SDVSecVtx_LxySig_max_val1]
  - [MET_pt_corr,SDVSecVtx_LxySig_max_val2]
  - [MET_pt_corr,SDVSecVtx_LxySig_max_2tk]
  - [MET_pt_corr,SDVSecVtx_LxySig_max_g2tk]
  - [nGoodTrack, LeadingVtx_nGoodTrack]
  - [nSDVTrack, LeadingVtx_nGoodTrack]

objects:


plot_setting:
  LHE_HT: [LHE_HT, ';LHE HT (GeV);A.U.', 500, 0, 5000]
  MET_pt: [MET_pt, ';MET (GeV);A.U.', 100, 0, 1000]
  MET_pt_corr: [MET_pt_corr, ';MET (xy corrected) (GeV);A.U.', 100, 0, 1000]
  leadingjet_pt: [leadingjet_pt, ';leading jet pT(GeV);A.U.', 100, 0, 1000]
  leadingjet_phi: [leadingjet_phi, ';leading jet #phi;A.U.', 128, -3.2, 3.2]
  leadingjet_eta: [leadingjet_eta, ';leading jet #eta;A.U.', 200, -5, 5]
  MET_phi: [MET_phi,";MET #phi;A.U.",128,-3.2,3.2]
  MET_phi_corr: [MET_phi_corr,";MET (xy corrected) #phi;A.U.",128,-3.2,3.2]
  dphi_MET_jet0: [dphi_MET_jet0,";#Delta #phi(MET,jet0);A.U.",64,0,3.2]
  SDVTrack_dxy: [SDVTrack_dxy, ";track dxy (cm);A.U.",400,-20,20]
  SDVTrack_dxyError: [SDVTrack_dxyError,";track #sigma dxy (cm);A.U.",100,0,1]
  SDVTrack_dz: [SDVTrack_dz,";track dz (cm);A.U.",400,-20,20]
  SDVTrack_dzError: [SDVTrack_dzError,";track #sigma dz (cm);A.U.",100,0,1] 
  SDVTrack_normalizedChi2: [SDVTrack_normalizedChi2,";track norm Chi2;A.U.",100,0,5]
  SDVTrack_numberOfValidHits: [SDVTrack_numberOfValidHits,";track # valid hits;A.U.",50,0,50]
  SDVTrack_isHighPurity: [SDVTrack_isHighPurity,";track isHighPurity;A.U.",2,0,2]
  SDVTrack_pt: [SDVTrack_pt,";track pt (GeV);A.U.",100,0,50]
  SDVTrack_phi: [SDVTrack_phi,";track #phi;A.U.",128,-3.2,3.2]
  SDVTrack_eta: [SDVTrack_eta,";track #eta;A.U.",200,-5,5]
  SDVTrack_ptError: [SDVTrack_ptError,";track #sigma pt (GeV);A.U.",100,0,0.5]
  SDVTrack_dxydzratio: [SDVTrack_dxydzratio,";track |dxy/dz|;A.U.",100,0,1]
  SDVTrack_dphi_MET: [SDVTrack_dphi_MET,";#Delta #phi (track,MET);A.U.",64,0,3.2]
  SDVTrack_dphi_jet0: [SDVTrack_dphi_jet0,";#Delta #phi (track,jet0);A.U.",64,0,3.2]
  SDVTrack_dr03TkSumPt: [SDVTrack_dr03TkSumPt,";track dR03TkSumPt;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_all: [SDVTrack_pfAbsIso03_all, ";track absolute iso all;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_chg: [SDVTrack_pfAbsIso03_chg, ";track absolute iso chg;A.U.",200,0,100]
  SDVTrack_pfRelIso03_all: [SDVTrack_pfRelIso03_all, ";track relative iso all;A.U.",200,0,100]
  SDVTrack_pfRelIso03_chg: [SDVTrack_pfRelIso03_chg, ";track relative iso chg;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_all_mod: [SDVTrack_pfAbsIso03_all_mod, ";track absolute iso all;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_chg_mod: [SDVTrack_pfAbsIso03_chg_mod, ";track absolute iso chg;A.U.",200,0,100]
  SDVTrack_pfRelIso03_all_mod: [SDVTrack_pfRelIso03_all_mod, ";track relative iso all;A.U.",200,0,100]
  SDVTrack_pfRelIso03_chg_mod: [SDVTrack_pfRelIso03_chg_mod, ";track relative iso chg;A.U.",200,0,100]
  SDVTrack_ntk_dRcone: [SDVTrack_ntk_dRcone, ";track ntk in dR cone;A.U.",40,0,40]
  SDVTrack_sumpt_dRcone: [SDVTrack_sumpt_dRcone, ";track sumpt in dR cone;A.U.",100,0,50]
  SDVTrack_weight: [SDVTrack_weight, ";track weight;A.U.",100,0,1]
  SDVTrack_minJetdphi: [SDVTrack_minJetdphi,";min(#Delta#phi(track, jet));A.U.",64,0,3.2]
  SDVTrack_minJetdeta: [SDVTrack_minJetdeta,";min(#Delta#eta(track, jet));A.U.",100,0,5]
  SDVTrack_minJetdR: [SDVTrack_minJetdR,";min(#DeltaR(track, jet));A.U.",100,0,5]
  SDVTrack_minJetdR_pt: [SDVTrack_minJetdR_pt,";pt of jet with minimum dR with track;A.U.",100,0,100]
  SDVSecVtx_x: [SDVSecVtx_x, ';vertex x (cm);A.U.',400, -20, 20]
  SDVSecVtx_y: [SDVSecVtx_y, ';vertex y (cm);A.U.',400, -20, 20]
  SDVSecVtx_L_phi: [SDVSecVtx_L_phi,";vertex #phi;A.U.",128,-3.2,3.2]
  SDVSecVtx_L_eta: [SDVSecVtx_L_eta,";vertex #eta;A.U.",200,-5,5]
  SDVSecVtx_L_eta_abs: [SDVSecVtx_L_eta_abs, ';vertex |#eta|;A.U.', 200, 0, 10]
  SDVSecVtx_Lxy: [SDVSecVtx_Lxy, ';vertex L_{xy} (cm);A.U.', 100, 0, 10]
  SDVSecVtx_LxySig: [SDVSecVtx_LxySig, ';vertex L_{xy}/#sigmaL_{xy};A.U.', 500, 0, 100]
  SDVSecVtx_LxySig_max: [SDVSecVtx_LxySig_max, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_LxySig_max_2tk: [SDVSecVtx_LxySig_max_2tk, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_LxySig_max_g2tk: [SDVSecVtx_LxySig_max_g2tk, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_LxySig_max_val: [SDVSecVtx_LxySig_max_val, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_LxySig_max_val1: [SDVSecVtx_LxySig_max_val1, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_LxySig_max_val2: [SDVSecVtx_LxySig_max_val2, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_ParTScore: [SDVSecVtx_ParTScore, ';ParTScore;A.U.', 50, 0, 1]
  SDVSecVtx_chi2: [SDVSecVtx_chi2, ';vertex chi2;A.U.', 50, 0, 10]
  SDVSecVtx_dlen: [SDVSecVtx_dlen, ';vertex dlen (cm);A.U.', 100, 0, 10]
  SDVSecVtx_dlenSig: [SDVSecVtx_dlenSig, ';vertex dlen/#sigmadlen;A.U.', 500, 0, 100]
  SDVSecVtx_dphiMET: [SDVSecVtx_dphiMET, ';#Delta#phi(Lxy,MET)', 64, 0, 3.2]
  SDVSecVtx_dphijet0: [SDVSecVtx_dphijet0, ';#Delta#phi(Lxy,jet0)', 64, 0, 3.2]
  SDVSecVtx_matchedLLPIdx_bydau: [SDVSecVtx_matchedLLPIdx_bydau, ';vertex matched LLP idx;A.U.', 5, -1, 4]
  SDVSecVtx_matchedLLPnDau_bydau: [SDVSecVtx_matchedLLPnDau_bydau, ';vertex number of tracks matched with LLP;A.U.', 10, 0, 10]
  SDVSecVtx_nGoodTrack: [SDVSecVtx_nGoodTrack, ';vertex ngoodTrack;A.U.', 20, 0, 20]
  SDVSecVtx_nGoodRefitTrack: [SDVSecVtx_nGoodRefitTrack, ';vertex ngoodRefitTrack;A.U.', 20, 0, 20]
  SDVSecVtx_nTracks: [SDVSecVtx_nTracks, ';vertex nTracks;A.U.', 20, 0, 20]
  SDVSecVtx_ndof: [SDVSecVtx_ndof, ';vertex ndof;A.U.', 20, 0, 20]
  SDVSecVtx_normalizedChi2: [SDVSecVtx_normalizedChi2, ';vertex norm chi2;A.U.', 50, 0, 10]
  SDVSecVtx_pAngle: [SDVSecVtx_pAngle, ';vertex pAngle;A.U.', 64, 0, 3.2]
  SDVSecVtx_mass: [SDVSecVtx_mass, ';vertex inv. mass;A.U.',1000,0,10]
  nSDVSecVtx_sel: [nSDVSecVtx_sel, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx_sel_val: [nSDVSecVtx_sel_val, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx_sel_val1: [nSDVSecVtx_sel_val1, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx_sel_val2: [nSDVSecVtx_sel_val2, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx: [nSDVSecVtx, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx_sel_gen: [nSDVSecVtx_sel_gen, ';Number of vertices (with gen cut);A.U.', 20, 0, 20]
  Pileup_nPU: [Pileup_nPU,';nPU;A.U.',100,0,100]
  nMuon_sel: [nMuon_sel,';nMuons;A.U.',10,0,10]
  nEle_sel: [nEle_sel,';nEle;A.U.',10,0,10]
  nPhoton_sel: [nPhoton_sel,';nPhoton;A.U.',10,0,10]
  nTau_sel: [nTau_sel,';nTau;A.U.',10,0,10]
  nJet_sel: [nJet_sel,';nJet (selected);A.U.',20,0,20]
  nJet: [nJet,';nJet;A.U.',20,0,20]
  nSDVTrack: [nSDVTrack,';nTrack (SDVTrack);A.U.',200,0,200]
  leadingjet_chHEF: [leadingjet_chHEF,';chHEF jet0;A.U.',100,0,1]
  leadingjet_neHEF: [leadingjet_neHEF,';neHEF jet0;A.U.',100,0,1]
  PV_npvs: [PV_npvs,';npv;A.U.',100,0,100]
  PV_npvsGood: [PV_npvsGood,';npvgood;A.U.',100,0,100]
  puweight: [puweight,';puweight;A.U.',100,0,2]
  evt_weight: [evt_weight,';evt_weight;A.U.',100,-2,2]
  Pileup_nTrueInt: [Pileup_nTrueInt,';nTrueInt;A.U.',100,0,100]
  LeadingVtx_LxySig: [LeadingVtx_LxySig, ';leading vertex L_{xy}/#sigmaL_{xy};A.U.', 500, 0, 100]
  LeadingVtx_nGoodTrack: [LeadingVtx_nGoodTrack, ';leading vertex nGoodTrack;A.U.', 20, 0, 20]
  nGoodTrack: [nGoodTrack,';nGoodTrack;A.U.',100,0,100]

