### GLOBAL DEFINITIONS

muon_sel:   (Muon_looseId>0)           && (Muon_eta<2.4)     && (Muon_pt>10)
ele_sel:    (Electron_cutBased>=1)     && (Electron_eta<2.5) && (Electron_pt>10)
photon_sel: (Photon_cutBased>=1)       && (Photon_eta<2.5)   && (Photon_pt>15)
tau_sel:    (Tau_idDecayModeOldDMs>=1) && (Tau_eta<2.3)      && (Tau_pt>18)

jet_selHEM: (Jet_jetId==6) 
jet_sel: (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (new_jet_pt>20)
nJetHEM: "Sum((Jet_eta_selHEM>-3.0) && (Jet_eta_selHEM<-1.3) && (Jet_phi_selHEM>-1.57) && (Jet_phi_selHEM<-0.87))"
presel: HLT_PFMETNoMu120_PFMHTNoMu120_IDTight && nJet_sel>0 && leadingjet_pt>100 && Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_hfNoisyHitsFilter && Flag_BadChargedCandidateFilter && Flag_eeBadScFilter && Flag_ecalBadCalibFilter && nJetHEM==0 && dphi_MET_jet0>1.0 && nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0
# preselection: MET_pt_corr>400 && HLT_PFMETNoMu120_PFMHTNoMu120_IDTight && nJet_sel>0 && leadingjet_pt>100 && Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_hfNoisyHitsFilter && Flag_BadChargedCandidateFilter && Flag_eeBadScFilter && Flag_ecalBadCalibFilter && nJetHEM==0 && dphi_MET_jet0>1.0 && nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0

corrections:
  PU:
    path: "/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2018_UL/puWeights.json.gz"
    name: "Collisions18_UltraLegacy_goldenJSON"
    mode: "nominal"



new_variables:
  new_jet_pt:   Jet_pt_nom
  new_MET_pt:   MET_T1Smear_pt_unclustEnDown
  new_MET_phi:  MET_T1Smear_phi_unclustEnDown

  MET_corr:     SDV::METXYCorr_Met_MetPhi(new_MET_pt,new_MET_phi,run,"2018",false,PV_npvs)
  MET_pt_corr:  MET_corr.first
  MET_phi_corr: MET_corr.second

  SDVTrack_isInSV:      Track_isInSV(SDVIdxLUT_TrackIdx,nSDVTrack)
  SDVTrack_qoverp:      SDVTrack_charge/SDVTrack_pt
  SDVTrack_dxySig:      abs(SDVTrack_dxy)/SDVTrack_dxyError
  SDVTrack_dzSig:       abs(SDVTrack_dz)/SDVTrack_dzError
  SDVTrack_ptSig:       SDVTrack_pt / SDVTrack_ptError
  SDVTrack_dphi_jet0:   acos(cos(SDVTrack_phi-Jet_phi[0]))
  SDVTrack_deta_jet0:   abs(SDVTrack_eta-Jet_eta[0])
  SDVTrack_dR_jet0:     sqrt(SDVTrack_dphi_jet0*SDVTrack_dphi_jet0 + SDVTrack_deta_jet0*SDVTrack_deta_jet0)
  SDVTrack_dphi_MET:    acos(cos(SDVTrack_phi-MET_phi_corr))
  SDVTrack_dxydzratio:  abs(SDVTrack_dxy/SDVTrack_dz)
  SDVTrack_isGoodTrack: ((abs(SDVTrack_dxy)/SDVTrack_dxyError)>4 ) && (SDVTrack_normalizedChi2 < 5) && (SDVTrack_numberOfValidHits>13) && ( (SDVTrack_ptError/SDVTrack_pt)<0.015 ) && ( SDVTrack_dxydzratio>0.25 ) && ( acos(cos(SDVTrack_phi-Jet_phi[0]))>1 ) && ( acos(cos(SDVTrack_phi-MET_phi_corr))<1.5 ) && (SDVTrack_pfRelIso03_all<5)
  SDVSecVtx_nGoodTrack: SDVSecVtx_nGoodTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isGoodTrack,nSDVSecVtx)
  SDVSecVtx_dphiMET:    acos(cos(SDVSecVtx_L_phi-MET_phi_corr))
  SDVSecVtx_dphijet0:   acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))
  
  nMuon_sel:    ['Sum({0})',    muon_sel  ]
  nEle_sel:     ['Sum({0})',    ele_sel   ]
  nPhoton_sel:  ['Sum({0})',    photon_sel]
  nTau_sel:     ['Sum({0})',    tau_sel   ]
  nJet_sel:     ['Sum({0})',    jet_sel   ]


  Jet_pt_sel:  ['new_jet_pt[{0}]', jet_sel] 
  Jet_eta_sel: ['Jet_eta[{0}]',jet_sel]
  Jet_phi_sel: ['Jet_phi[{0}]',jet_sel]

  leadingjet_pt:  Jet_pt_sel[0]
  leadingjet_phi: Jet_phi_sel[0]


  Jet_eta_selHEM: ['Jet_eta[{0}]', jet_selHEM]
  Jet_phi_selHEM: ['Jet_phi[{0}]', jet_selHEM]

  dphi_MET_jet0: acos(cos(leadingjet_phi-MET_phi_corr))

  SRs_vertexCuts:  SDVSecVtx_ndof>1  && SDVSecVtx_pAngle>0.2 && SDVSecVtx_dphiMET<1.5 && acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 && SDVSecVtx_nGoodTrack>=2
  VR1s_vertexCuts:  SDVSecVtx_ndof>1  && SDVSecVtx_pAngle>0.2 && SDVSecVtx_dphiMET<1.5 && acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 && SDVSecVtx_nGoodTrack==1
  VR2s_vertexCuts:  SDVSecVtx_ndof>1  && SDVSecVtx_pAngle>0.2 && SDVSecVtx_dphiMET<1.5 && acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 && SDVSecVtx_nGoodTrack==0
  nGoodVtx_SRs:    Sum(SRs_vertexCuts)
  nGoodVtx_VR1s:    Sum(VR1s_vertexCuts)
  nGoodVtx_VR2s:    Sum(VR2s_vertexCuts)
  SRsMaxLxySig:    Max(SDVSecVtx_LxySig[SRs_vertexCuts])
  VR1sMaxLxySig:    Max(SDVSecVtx_LxySig[VR1s_vertexCuts])
  VR2sMaxLxySig:    Max(SDVSecVtx_LxySig[VR2s_vertexCuts])

regions:
  All: 
  # presele: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0
  SRs:      nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nGoodVtx_SRs>0
  VR1s:      nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nGoodVtx_SRs==0 && nGoodVtx_VR1s>0
  VR2s:      nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nGoodVtx_SRs==0 && nGoodVtx_VR1s==0 && nGoodVtx_VR2s>0

event_variables:
- MET_pt_corr
- SRsMaxLxySig
- VR1sMaxLxySig
- VR2sMaxLxySig
event_2d_plots:
  - [MET_pt_corr,SRsMaxLxySig]
  - [MET_pt_corr,VR1sMaxLxySig]
  - [MET_pt_corr,VR2sMaxLxySig]
objects:

plot_setting:
  MET_pt_corr:  [MET_pt_corr, ';MET_corr (GeV);A.U.', 100, 0, 1000]
  SRsMaxLxySig:  [SRsMaxLxySig, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  VR1sMaxLxySig:  [VR1sMaxLxySig, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  VR2sMaxLxySig:  [VR2sMaxLxySig, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]



