### GLOBAL DEFINITIONS

muon_sel:   (Muon_looseId>0)           && (Muon_eta<2.4)     && (Muon_pt>10)
ele_sel:    (Electron_cutBased>=1)     && (Electron_eta<2.5) && (Electron_pt>10)
photon_sel: (Photon_cutBased>=1)       && (Photon_eta<2.5)   && (Photon_pt>15)
tau_sel:    (Tau_idDecayModeOldDMs>=1) && (Tau_eta<2.3)      && (Tau_pt>18)

bjetgen: Jet_hadronFlavour>=4 && Jet_hadronFlavour<=5
jet_selHEM: (Jet_jetId==6) 
jet_sel:    (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (Jet_pt>20)
bjetloose:  (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (Jet_pt>20) && Jet_btagDeepFlavB>0.50
bjetmedium: (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (Jet_pt>20) && Jet_btagDeepFlavB>0.80
bjettight:  (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (Jet_pt>20) && Jet_btagDeepFlavB>0.71
bjetultratight:  (Jet_jetId==6) && (abs(Jet_eta)<2.4) && (Jet_neHEF<0.8) && (Jet_chHEF>0.1) && (Jet_pt>20) && Jet_btagDeepFlavB>0.98
nJetHEM: "Sum((Jet_eta_selHEM>-3.0) && (Jet_eta_selHEM<-1.3) && (Jet_phi_selHEM>-1.57) && (Jet_phi_selHEM<-0.87))"
presel: HLT_PFMETNoMu120_PFMHTNoMu120_IDTight && nJet_sel>0 && leadingjet_pt>100 && Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_hfNoisyHitsFilter && Flag_BadChargedCandidateFilter && Flag_eeBadScFilter && Flag_ecalBadCalibFilter && nJetHEM==0 && dphi_MET_jet0>1.0 && nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0
# preselection: MET_pt_corr>400 && HLT_PFMETNoMu120_PFMHTNoMu120_IDTight && nJet_sel>0 && leadingjet_pt>100 && Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_hfNoisyHitsFilter && Flag_BadChargedCandidateFilter && Flag_eeBadScFilter && Flag_ecalBadCalibFilter && nJetHEM==0 && dphi_MET_jet0>1.0 && nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0

corrections:
  PU:
    "2017":
      path: "/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2017_UL/puWeights.json.gz"
      name: "Collisions17_UltraLegacy_goldenJSON"
      mode: "nominal"
    "2018":
      path: "/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2018_UL/puWeights.json.gz"
      name: "Collisions18_UltraLegacy_goldenJSON"
      mode: "nominal"
  met:
    mode: "nominal"
  # objects:
  #   SDVSecVtx:

  weights:

  mcweights:
    - L1PreFiringWeight_Nom 


new_variables:

  SDVTrack_isInSV:      Track_isInSV(SDVIdxLUT_TrackIdx,nSDVTrack)
  SDVTrack_qoverp:      SDVTrack_charge/SDVTrack_pt
  SDVTrack_dxySig:      abs(SDVTrack_dxy)/SDVTrack_dxyError
  SDVTrack_dzSig:       abs(SDVTrack_dz)/SDVTrack_dzError
  SDVTrack_ptSig:       SDVTrack_pt / SDVTrack_ptError
  SDVTrack_dphi_jet0:   acos(cos(SDVTrack_phi-Jet_phi[0]))
  SDVTrack_deta_jet0:   abs(SDVTrack_eta-Jet_eta[0])
  

  SDVTrack_dR_jet0:     sqrt(SDVTrack_dphi_jet0*SDVTrack_dphi_jet0 + SDVTrack_deta_jet0*SDVTrack_deta_jet0)
  SDVTrack_dphi_MET:    acos(cos(SDVTrack_phi-MET_phi_corr))
  SDVTrack_dxydzratio:  abs(SDVTrack_dxy/SDVTrack_dz)
  SDVTrack_isGoodTrack: ((abs(SDVTrack_dxy)/SDVTrack_dxyError)>4 ) && (SDVTrack_normalizedChi2 < 5) && (SDVTrack_numberOfValidHits>13) && ( (SDVTrack_ptError/SDVTrack_pt)<0.015 ) && ( SDVTrack_dxydzratio>0.25 ) && ( acos(cos(SDVTrack_phi-Jet_phi[0]))>1 ) && ( acos(cos(SDVTrack_phi-MET_phi_corr))<1.5 ) && (SDVTrack_pfRelIso03_all<5)
  SDVTrack_isGoodTrack_b: SDVTrack_normalizedChi2<5 && SDVTrack_numberOfValidHits>13 && SDVTrack_ptError/SDVTrack_pt<0.015 && SDVTrack_dxydzratio>0.25 && (abs(SDVTrack_dxy)/SDVTrack_dxyError)>4

  SDVSecVtx_ngoodtk:  SDVSecVtx_nGoodTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isGoodTrack,nSDVSecVtx)
  SDVSecVtx_ngoodtkb: SDVSecVtx_nGoodTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isGoodTrack_b,nSDVSecVtx)
  
  SDVSecVtx_TkMaxdphi: "SDV_TkMaxdphi(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_phi)"
  SDVSecVtx_TkMindphi: "SDV_TkMindphi(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_phi)"
  SDVSecVtx_TkMaxdeta: "SDV_TkMaxdphi(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_eta)"
  SDVSecVtx_TkMindeta: "SDV_TkMindphi(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_eta)"
  SDVSecVtx_TkMaxdR: "SDV_TkMaxdR(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_eta, SDVTrack_phi)"
  SDVSecVtx_TkMindR: "SDV_TkMindR(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_eta, SDVTrack_phi)"
  

  SDVSecVtx_dphiMET:    acos(cos(SDVSecVtx_L_phi-MET_phi_corr))
  SDVSecVtx_dphijet0:   acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))


  bJet_phi_loose : ['Jet_phi[{0}]', bjetloose]
  bJet_eta_loose : ['Jet_eta[{0}]', bjetloose]

  bJet_phi_medium : ['Jet_phi[{0}]', bjetmedium]
  bJet_eta_medium : ['Jet_eta[{0}]', bjetmedium]

  bJet_phi_tight : ['Jet_phi[{0}]', bjettight]
  bJet_eta_tight : ['Jet_eta[{0}]', bjettight]

  bJet_phi_ultratight : ['Jet_phi[{0}]', bjetultratight]
  bJet_eta_ultratight : ['Jet_eta[{0}]', bjetultratight]

  bjetloose :  ['{0}', bjetloose]
  bjetmedium : ['{0}', bjetmedium]
  bjettight :  ['{0}', bjettight]
  bjetultratight :  ['{0}', bjetultratight]

  nbJet_tight:      ['Sum({0})',bjettight]
  nbJet_ultratight: ['Sum({0})',bjettight]

  Jet_nTracks_dR0p2 :     GetJetnTracks(SDVTrack_pt, SDVTrack_phi, SDVTrack_eta, Jet_phi, Jet_eta, 0.2, 0.0)
  Jet_nTracks_dR0p4 :     GetJetnTracks(SDVTrack_pt, SDVTrack_phi, SDVTrack_eta, Jet_phi, Jet_eta, 0.4, 0.0)
  Jet_nTracks_dR0p2_pt1 : GetJetnTracks(SDVTrack_pt, SDVTrack_phi, SDVTrack_eta, Jet_phi, Jet_eta, 0.2, 1.0)
  Jet_nTracks_dR0p4_pt1 : GetJetnTracks(SDVTrack_pt, SDVTrack_phi, SDVTrack_eta, Jet_phi, Jet_eta, 0.4, 1.0)

  SDVSecVtx_mindRdphidetabJet_loose: "Vertex_mindRdetadphi(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_loose,bJet_eta_loose)"
  SDVSecVtx_closestbJetdR_loose:   "SDVSecVtx_mindRdphidetabJet_loose[0]"
  SDVSecVtx_closestbJetdphi_loose: "SDVSecVtx_mindRdphidetabJet_loose[1]"
  SDVSecVtx_closestbJetdeta_loose: "SDVSecVtx_mindRdphidetabJet_loose[2]"

  SDVSecVtx_mindRdphidetabJet_medium: "Vertex_mindRdetadphi(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_medium,bJet_eta_medium)"
  SDVSecVtx_closestbJetdR_medium:   "SDVSecVtx_mindRdphidetabJet_medium[0]"
  SDVSecVtx_closestbJetdphi_medium: "SDVSecVtx_mindRdphidetabJet_medium[1]"
  SDVSecVtx_closestbJetdeta_medium: "SDVSecVtx_mindRdphidetabJet_medium[2]"

  SDVSecVtx_mindRdphidetabJet_tight:  "Vertex_mindRdetadphi(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_tight,bJet_eta_tight)"
  SDVSecVtx_closestbJetdR_tight:      "SDVSecVtx_mindRdphidetabJet_tight[0]"
  SDVSecVtx_closestbJetdphi_tight:    "SDVSecVtx_mindRdphidetabJet_tight[1]"
  SDVSecVtx_closestbJetdeta_tight:    "SDVSecVtx_mindRdphidetabJet_tight[2]"

  SDVSecVtx_mindRdphidetabJet_ultratight:  "Vertex_mindRdetadphi(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_ultratight,bJet_eta_ultratight)"
  SDVSecVtx_closestbJetdR_ultratight:      "SDVSecVtx_mindRdphidetabJet_ultratight[0]"
  SDVSecVtx_closestbJetdphi_ultratight:    "SDVSecVtx_mindRdphidetabJet_ultratight[1]"
  SDVSecVtx_closestbJetdeta_ultratight:    "SDVSecVtx_mindRdphidetabJet_ultratight[2]"

  SDVSecVtx_minmaxtkdxy: SDV_TkMinMaxdxy(SDVIdxLUT_TrackIdx, SDVIdxLUT_SecVtxIdx, nSDVSecVtx, SDVTrack_dxy)
  SDVSecVtx_TkMindxy:    SDVSecVtx_minmaxtkdxy[0]
  SDVSecVtx_TkMaxdxy:    SDVSecVtx_minmaxtkdxy[1]

  SDVSecVtx_closestbJetidx_loose: "vtx_jetidx_at_mindR(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_loose,bJet_eta_loose)"
  SDVSecVtx_closestbJet_btagDeepFlavB_loose: ROOT::VecOps::Take(Jet_btagDeepFlavB[bjetloose], SDVSecVtx_closestbJetidx_loose)

  SDVSecVtx_closestbJetidx_medium: "vtx_jetidx_at_mindR(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_medium,bJet_eta_medium)"
  SDVSecVtx_closestbJet_btagDeepFlavB_medium: ROOT::VecOps::Take(Jet_btagDeepFlavB[bjetmedium], SDVSecVtx_closestbJetidx_medium)

  SDVSecVtx_closestbJetidx_tight: "vtx_jetidx_at_mindR(SDVSecVtx_L_phi,SDVSecVtx_L_eta,bJet_phi_tight,bJet_eta_tight)"
  SDVSecVtx_closestbJet_btagDeepFlavB_tight: ROOT::VecOps::Take(Jet_btagDeepFlavB[bjettight], SDVSecVtx_closestbJetidx_tight)

  
  nMuon_sel:    ['Sum({0})',    muon_sel  ]
  nEle_sel:     ['Sum({0})',    ele_sel   ]
  nPhoton_sel:  ['Sum({0})',    photon_sel]
  nTau_sel:     ['Sum({0})',    tau_sel   ]
  nJet_sel:     ['Sum({0})',    jet_sel   ]

  b0_sel_nodR:   (SDVSecVtx_mass<0.4 || SDVSecVtx_mass>0.6) && SDVSecVtx_ndof>1


  Jet_pt_sel:  ['Jet_pt[{0}]', jet_sel] 
  Jet_eta_sel: ['Jet_eta[{0}]',jet_sel]
  Jet_phi_sel: ['Jet_phi[{0}]',jet_sel]

  leadingjet_pt:  Jet_pt_sel[0]
  leadingjet_phi: Jet_phi_sel[0]

  Jet_eta_selHEM: ['Jet_eta[{0}]', jet_selHEM]
  Jet_phi_selHEM: ['Jet_phi[{0}]', jet_selHEM]

  dphi_MET_jet0: acos(cos(leadingjet_phi-MET_phi_corr))

new_variables_mc:

regions:
  MET200: MET_pt_corr>200
  MET400: MET_pt_corr>400

event_variables:
- MET_pt_corr
- nbJet_tight
- nbJet_ultratight

event_2d_plots:

objects:
  SDVSecVtx:
    selections:
      tight:       b0_sel_nodR  && SDVSecVtx_ngoodtkb>=1
    variables:
      - SDVSecVtx_closestbJetdR_tight
      # - SDVSecVtx_closestbJetdphi_tight
      # - SDVSecVtx_closestbJetdeta_tight
      # - SDVSecVtx_closestbJet_btagDeepFlavB_tight
      # - SDVSecVtx_TkMaxdphi
      # - SDVSecVtx_TkMindphi
      # - SDVSecVtx_TkMaxdeta
      # - SDVSecVtx_TkMindeta
      # - SDVSecVtx_TkMaxdR
      # - SDVSecVtx_TkMindR
      # - SDVSecVtx_TkMindxy
      # - SDVSecVtx_TkMaxdxy
    2d_plots:

plot_setting:
  MET_pt_corr:      [MET_pt_corr, ';MET_corr (GeV);Counts', 100, 0, 1000]
  nbJet_tight:      [nbJet_tight,      ';nbJet_tight;Counts',      8, 0, 8]
  nbJet_ultratight: [nbJet_ultratight, ';nbJet_ultratight;Counts', 8, 0, 8]

  SDVSecVtx_mass:       [SDVSecVtx_mass,     ';SDVSecVtx_mass (GeV);Counts', 100, 1, 2]
  SDVSecVtx_Lxy:        [SDVSecVtx_Lxy,      ';SDVSecVtx_Lxy (cm);Counts', 40, 0, 40]
  SDVSecVtx_LxySig:     [SDVSecVtx_LxySig,   ';SDVSecVtx_LxySig;Counts', 40, 0, 400]
  SDVSecVtx_pAngle:     [SDVSecVtx_pAngle,   ';SDVSecVtx_pAngle (rad);Counts', 64, 0, 3.2]
  SDVSecVtx_dphiMET:    [SDVSecVtx_dphiMET,  ';SDVSecVtx_dphiMET (rad);Counts', 50, 0, 4]
  SDVSecVtx_dphijet0:   [SDVSecVtx_dphijet0, ';SDVSecVtx_dphijet0 (rad);Counts', 50, 0, 4]
  SDVSecVtx_nTracks:    [SDVSecVtx_nTracks,  ';SDVSecVtx_nTracks ;Counts', 20, 0, 20]
  SDVSecVtx_ngoodtk:    [SDVSecVtx_ngoodtk,  ';SDVSecVtx_ngoodtk ;Counts', 20, 0, 20]
  SDVSecVtx_ngoodtkb:   [SDVSecVtx_ngoodtkb, ';SDVSecVtx_ngoodtkb ;Counts', 20, 0, 20]
  SDVSecVtx_ndof:       [SDVSecVtx_ndof,     ';SDVSecVtx_ndof ;Counts', 10, 0, 10]
  SDVSecVtx_charge:     [SDVSecVtx_charge,   ';SDVSecVtx_charge ;Counts', 9, -4.5, 4.5]

  
  SDVSecVtx_closestbJetdR_loose:              [SDVSecVtx_closestbJetdR_loose, ';SDVSecVtx_closestbJetdR_loose;Counts', 40, 0, 5]
  SDVSecVtx_closestbJetdR_medium:             [SDVSecVtx_closestbJetdR_medium, ';SDVSecVtx_closestbJetdR_medium;Counts', 40, 0, 5]
  SDVSecVtx_closestbJetdR_tight:              [SDVSecVtx_closestbJetdR_tight, ';SDVSecVtx_closestbJetdR_tight;Counts', 40, 0, 5]
  SDVSecVtx_closestbJetdR_gen:                [SDVSecVtx_closestbJetdR_gen, ';SDVSecVtx_closestbJetdR_gen;Counts', 40, 0, 5]
  SDVSecVtx_closestbJetdphi_loose:            [SDVSecVtx_closestbJetdphi_loose,  ';SDVSecVtx_closestbJetdphi_loose;Counts', 40, 0, 4]
  SDVSecVtx_closestbJetdphi_medium:           [SDVSecVtx_closestbJetdphi_medium, ';SDVSecVtx_closestbJetdphi_medium;Counts', 40, 0, 4]
  SDVSecVtx_closestbJetdphi_tight:            [SDVSecVtx_closestbJetdphi_tight,  ';SDVSecVtx_closestbJetdphi_tight;Counts', 40, 0, 4]
  SDVSecVtx_closestbJetdphi_gen:              [SDVSecVtx_closestbJetdphi_gen,  ';SDVSecVtx_closestbJetdphi_gen;Counts', 40, 0, 4]
  SDVSecVtx_closestbJetdeta_loose:            [SDVSecVtx_closestbJetdeta_loose, ';SDVSecVtx_closestbJetdeta_loose;Counts', 100, 0, 5]
  SDVSecVtx_closestbJetdeta_medium:           [SDVSecVtx_closestbJetdeta_medium, ';SDVSecVtx_closestbJetdeta_medium;Counts', 100, 0, 5]
  SDVSecVtx_closestbJetdeta_tight:            [SDVSecVtx_closestbJetdeta_tight, ';SDVSecVtx_closestbJetdeta_tight;Counts', 100, 0, 5]
  SDVSecVtx_closestbJetdeta_gen:              [SDVSecVtx_closestbJetdeta_gen, ';SDVSecVtx_closestbJetdeta_gen;Counts', 100, 0, 5]
  SDVSecVtx_closestbJet_btagDeepFlavB_loose:  [SDVSecVtx_closestbJet_btagDeepFlavB_loose, ';SDVSecVtx_closestbJet_btagDeepFlavB_loose;Counts', 100, 0.50, 1]
  SDVSecVtx_closestbJet_btagDeepFlavB_medium: [SDVSecVtx_closestbJet_btagDeepFlavB_medium, ';SDVSecVtx_closestbJet_btagDeepFlavB_medium;Counts', 40, 0.80, 1]
  SDVSecVtx_closestbJet_btagDeepFlavB_tight:  [SDVSecVtx_closestbJet_btagDeepFlavB_tight, ';SDVSecVtx_closestbJet_btagDeepFlavB_tight;Counts', 100, 0.50, 1]
  SDVSecVtx_closestbJet_btagDeepFlavB_gen:    [SDVSecVtx_closestbJet_btagDeepFlavB_gen, ';SDVSecVtx_closestbJet_btagDeepFlavB_gen;Counts', 100, 0.50, 1]
  
  
  SDVSecVtx_TkMaxdphi: [SDVSecVtx_TkMaxdphi, ';SDVSecVtx_TkMaxdphi;Counts', 50, 0, 4]
  SDVSecVtx_TkMindphi: [SDVSecVtx_TkMindphi, ';SDVSecVtx_TkMindphi;Counts', 50, 0, 4]
  SDVSecVtx_TkMaxdeta: [SDVSecVtx_TkMaxdeta, ';SDVSecVtx_TkMaxdeta;Counts', 50, 0, 10]
  SDVSecVtx_TkMindeta: [SDVSecVtx_TkMindeta, ';SDVSecVtx_TkMindeta;Counts', 50, 0, 10]
  SDVSecVtx_TkMaxdR:   [SDVSecVtx_TkMaxdR,   ';SDVSecVtx_TkMaxdR;Counts', 50, 0, 10]
  SDVSecVtx_TkMindR:   [SDVSecVtx_TkMindR,   ';SDVSecVtx_TkMindR;Counts', 50, 0, 10]
  SDVSecVtx_TkMindxy:  [SDVSecVtx_TkMindxy,  ';SDVSecVtx_TkMindxy;Counts', 20, 0, 20]
  SDVSecVtx_TkMaxdxy:  [SDVSecVtx_TkMaxdxy,  ';SDVSecVtx_TkMaxdxy;Counts', 20, 0, 20]

  Jet_btagDeepFlavB:      [Jet_btagDeepFlavB,     ';Jet_btagDeepFlavB;Counts', 100, 0, 1]
  Jet_mass:               [Jet_mass,              ';Jet_mass (GeV);Counts', 200, 0, 20]
  Jet_nConstituents:      [Jet_nConstituents,     ';Jet_nConstituents;Counts', 20, 0, 100]
  Jet_nTracks_dR0p2:      [Jet_nTracks_dR0p2,     ';Jet_nTracks_dR0p2;Counts',     40, 0, 40]
  Jet_nTracks_dR0p4:      [Jet_nTracks_dR0p4,     ';Jet_nTracks_dR0p4;Counts',     40, 0, 40]
  Jet_nTracks_dR0p2_pt1:  [Jet_nTracks_dR0p2_pt1, ';Jet_nTracks_dR0p2_pt1;Counts', 40, 0, 40]
  Jet_nTracks_dR0p4_pt1:  [Jet_nTracks_dR0p4_pt1, ';Jet_nTracks_dR0p4_pt1;Counts', 40, 0, 40]



